### ISSUE TITLE
Integrate the ACRA crash reporting library

### ISSUE THREAD

**Issue by tjg1** [tjg1/nori#98]
> [ACRA](https://github.com/ACRA/acra) is a library enabling Android Application to automatically post their crash reports to a report server. It is targeted to android applications developers to help them get data from their applications when they crash or behave erroneously.

ACRA is a free and open source crash reporting library for Android, allowed under F-Droid's free software inclusion policy. Adding it would allow us to gather crash reports from devices using the `fdroid` build of Nori, without relying on Google Play Services or a proprietary library such as Crashlytics.

To respect our users' privacy, we need to make sure that the user can choose whether they want to submit the bug report or not. Not doing so would cause it to get marked as an "anti-feature" by the F-Droid maintainers.

#### Action Plan

- [ ] Add a new dependency to Nori's Gradle build file
- [ ] Create an Application class and attach ACRA's exception hook
- [ ] Configure crash report user prompt (important)
- [ ] Set up crash report backend (may need to self-host)
- [ ] Ensure compatibility with ProGuard/Jack builds

#### Useful Links 
- https://github.com/ACRA/acra
- https://github.com/ACRA/acra/wiki/BasicSetup
- https://github.com/ACRA/acra/wiki/AdvancedUsage
- https://github.com/ACRA/acralyzer
- https://github.com/ACRA/acra/wiki/ProGuard
- https://stackoverflow.com/questions/7476574/android-how-to-verify-successful-installation-of-acra-crash-logging
